apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
      securityContext:
        fsGroup: 999  # docker 그룹 ID
      containers:
      - name: github-runner
        image: sclee1115/github-runner-custom:v0.0.10
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "2Gi"
            cpu: "1000m"
            ephemeral-storage: "2Gi"
        env:
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUNNER_REPOSITORY_URL
          value: "https://github.com/ulmsaga/msa_team3"
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-secret
              key: RUNNER_TOKEN
        volumeMounts:
        - name: workdir
          mountPath: /_work
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: maven-cache
          mountPath: /home/github-runner/.m2
      volumes:
      - name: workdir
        emptyDir: {}
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: maven-cache
        persistentVolumeClaim:
          claimName: maven-cache-pvc