apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: github-runner
        image: sclee1115/github-runner-custom:v0.0.6
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 512Mi
          limits:
            cpu: 200m
            memory: 256Mi
            ephemeral-storage: 1Gi
        env:
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUNNER_REPOSITORY_URL
          value: "https://github.com/ulmsaga/msa_team3"
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-secret
              key: RUNNER_TOKEN
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "2Gi"
        volumeMounts:
        - name: workdir
          mountPath: /_work
      volumes:
      - name: workdir
        emptyDir: {}