apiVersion: v1
kind: PersistentVolume
metadata:
  name: team3-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/DATA1/team3/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: team3-postgres-pvc
  namespace: group1-team3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: team3-postgres-pv