spring:
  config:
    import: "optional:configserver:http://localhost:9200/"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9201/eureka/