apiVersion: apps/v1
kind: Deployment
metadata:
  name: team3-lsc-gatewayserver-deployment
  namespace: group1-team3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team3-lsc-gatewayserver-app
  template:
    metadata:
      labels:
        app: team3-lsc-gatewayserver-app
    spec:
      containers:
      - name: team3-lsc-gatewayserver-container
        image: k8s-vga-worker1:5000/group1-team3-lsc-gatewayserver:v0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 9202
---
apiVersion: v1
kind: Service
metadata:
  name: team3-lsc-gatewayserver-service
  namespace: group1-team3
spec:
  selector:
    app: team3-lsc-gatewayserver-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9202
      nodePort: 30312
  type: NodePort
