apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: group1-team3
spec:
  selector:
    app: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: 2181

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  namespace: group1-team3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          #bitnami/zookeeper:latest
          image: k8s-vga-worker1:5000/zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          volumeMounts:
            - name: zk-data
              mountPath: /var/lib/zookeeper/data
            - name: zk-logs
              mountPath: /var/lib/zookeeper/logs
      volumes:
        - name: zk-data
          emptyDir: {}
        - name: zk-logs
          emptyDir: {}
