apiVersion: apps/v1
kind: Deployment
metadata:
  name: team3-lsc-message-deployment
  namespace: group1-team3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team3-lsc-message-app
  template:
    metadata:
      labels:
        app: team3-lsc-message-app
    spec:
      containers:
      - name: team3-lsc-message-container
        image: k8s-vga-worker1:5000/group1-team3-lsc-message:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9203
---
apiVersion: v1
kind: Service
metadata:
  name: team3-lsc-message-service
  namespace: group1-team3
spec:
  selector:
    app: team3-lsc-message-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9203
      nodePort: 30313
  type: NodePort
