apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configserver
  namespace: group1-team3
spec:
  project: default
  source:
    repoURL: https://github.com/ulmsaga/msa_team3.git
    targetRevision: main
    path: helmcharts/configserver
  destination:
    server: https://kubernetes.default.svc
    namespace: group1-team3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true