apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: group1-team3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672  # AMQP port
            - containerPort: 15672 # Management UI port
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: group1-team3
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30313
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 30314
  type: NodePort
