apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: group1-team3-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["argoproj.io"]  # ArgoCD API 그룹 추가
  resources: ["applications", "appprojects"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: group1-team3-admin-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: group1-team3
roleRef:
  kind: ClusterRole
  name: group1-team3-admin
  apiGroup: rbac.authorization.k8s.io