name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: |
          cd configserver
          mvn clean install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sclee1115
          password: saseopaseo00

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./configserver  # Dockerfile이 있는 경로를 지정합니다
          file: ./configserver/Dockerfile  # Dockerfile의 경로를 지정합니다
          push: true
          # tags: 127.0.0.1:5001/group1-team3-lsc-configserver:latest
          tags: sclee1115/group1-team3-lsc-configserver:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes using Helm and ArgoCD
        env:
          # KUBECONFIG: ${{ secrets.KUBECONFIG }}
          KUBECONFIG: $HOME/.kube/config # 수정된 부분: 디코딩된 kubeconfig 파일 경로를 설정합니다.
        run: |
          helm upgrade --install configserver ./configserver/helmchart --namespace group1-team3 --debug
          argocd app sync configserver