name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'services/configserver/**'
      - 'helmcharts/configserver/**'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: |
          cd services/configserver
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      # Helm 업데이트
      - name: Update Helm values
        env:
          GH_TOKEN: ${{ secrets.GH_FOR_HELM_IN_WORKFLOW }}
        run: |
          cd helmcharts/configserver
          
          # ...existing code...

          # 호스트 IP 확인 (대체 방법)
          HOST_IP=$(hostname -i || hostname -I || echo "127.0.0.1")
          echo "Host IP: ${HOST_IP}"
          
          # ArgoCD 서버 상태 확인
          echo "Checking ArgoCD server status..."
          kubectl get svc argocd-server -n group1-team3
          
          # 서비스 IP 직접 사용
          ARGOCD_SERVER_IP=$(kubectl get svc argocd-server -n group1-team3 -o=jsonpath='{.spec.clusterIP}')
          echo "ArgoCD Server IP: ${ARGOCD_SERVER_IP}"
          
          # ArgoCD 로그인
          echo "Logging into ArgoCD..."
          argocd login ${ARGOCD_SERVER_IP} \
            --username admin \
            --password 'akfxlwm40__-' \
            --insecure \
            --port 80
          
          # 동기화 상태 확인
          echo "Syncing ArgoCD application..."
          argocd app sync configserver --force